services:
    elk_bridge.event_bus.log_event:
        class: Clearcode\ElkBridgeBundle\CommandBus\LogEventMiddleware
        arguments:
            - @logger
            - @elk_bridge.converter.to_array_converter
        tags:
            - { name: event_bus_middleware, priority: 999 }
            - { name: monolog.logger, channel: '%elk_bridge.channel%' }