services:
    elk_bridge.converter.to_array_converter:
        class: Clearcode\ElkBridgeBundle\Converter\ObjectToArrayConverter
        arguments:
            - @jms_serializer
    elk_bridge.monolog.logstash_formatter:
        class: Monolog\Formatter\LogstashFormatter
        arguments: [ "%elk_bridge.logstash_namespace%" ]
