services:
    simple_bus_elk.logstash:
        class: Clearcode\SimpleBusElkBundle\Logstash\Logstash
        arguments:
            - @logger
            - @simple_bus_elk.converter.to_array_converter
        tags:
            - { name: monolog.logger, channel: '%simple_bus_elk.monolog_channel%' }
